use ecommercedb;

-- Task 3
-- Writing basic select queries
-- Selecting all the columns from the data
SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM SALES;

-- Selecting specific columns from tables
SELECT CUSTOMER_ID,NAME,EMAIL FROM CUSTOMERS;
SELECT NAME,PRICE FROM PRODUCTS;
SELECT CUSTOMER_ID,ORDER_DATE FROM ORDERS;

-- Applying where, And, Between, or, Like
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID = 1;
SELECT NAME, PRICE FROM PRODUCTS WHERE PRICE > 100;
SELECT NAME , PRICE FROM PRODUCTS WHERE PRICE BETWEEN 100 AND 1000;
SELECT * FROM ORDERS WHERE ORDER_DATE = '2025-09-22' AND CUSTOMER_ID = 1;
SELECT * FROM CUSTOMERS WHERE NAME LIKE 'R%';
SELECT * FROM CUSTOMERS WHERE NAME LIKE '%ESH';
SELECT NAME , PRICE FROM PRODUCTS WHERE PRICE < 500 OR PRICE > 1000;

-- Sorting Data with ORDER BY
SELECT NAME, PRICE FROM PRODUCTS ORDER BY PRICE DESC;
SELECT * FROM ORDERS ORDER BY ORDER_DATE DESC;

-- LIMIT 
SELECT NAME, PRICE FROM PRODUCTS ORDER BY PRICE DESC LIMIT 2;
